### ISSUE TITLE
wrong unlock password error message

### ISSUE THREAD

**Issue by littleskunk** [Storj/node-storj#24]
Please add a error message for wrong unlock password

```
root@node-storj:~# storj
 :STORJ: >> Unlock your private key to start storj >>  ********

readline.js:924
            throw err;
            ^

Error: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt
    at Error (native)
    at Decipher.Cipher.final (crypto.js:153:26)
    at decrypt (/root/.nvm/versions/node/v4.2.3/lib/node_modules/storj/bin/storj.js:143:18)
    at /root/.nvm/versions/node/v4.2.3/lib/node_modules/storj/bin/storj.js:173:15
    at /root/.nvm/versions/node/v4.2.3/lib/node_modules/storj/node_modules/prompt/lib/prompt.js:336:32
    at /root/.nvm/versions/node/v4.2.3/lib/node_modules/storj/node_modules/prompt/node_modules/utile/node_modules/async/lib/async.js:154:25
    at assembler (/root/.nvm/versions/node/v4.2.3/lib/node_modules/storj/node_modules/prompt/lib/prompt.js:333:9)
    at /root/.nvm/versions/node/v4.2.3/lib/node_modules/storj/node_modules/prompt/lib/prompt.js:342:32
    at /root/.nvm/versions/node/v4.2.3/lib/node_modules/storj/node_modules/prompt/lib/prompt.js:625:5
    at Interface.onLine (/root/.nvm/versions/node/v4.2.3/lib/node_modules/storj/node_modules/prompt/node_modules/read/lib/read.js:111:5)
```

**Comment by gordonwritescode** [comment]
Resolved - will be included in next release
