### ISSUE TITLE
wan ip address not working

### ISSUE THREAD

**Issue by littleskunk** [Storj/node-storj#25]
Invalid ip addresses are allowed:
0.0.0.0
127.0.0.1
192.168.1.2
255.255.255.255
Maybe a dns name if i add it to my local dns service. I didn't check it.

My public ip address is not working. I get this error message:
```
root@node-storj:~# storj
 :STORJ: >> Unlock your private key to start storj >>  ********

 :STORJ: {info} node created with nodeID a89b7babbd7b4071b9e6e605734223620dc301ce
 :STORJ: {info} subscribing to topic "56ce3e837f575827cb5a94e2b609756a48fa4a3882f5e762b262af31f432878d"
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRNOTAVAIL 91.61.66.100:4001
    at Object.exports._errnoException (util.js:874:11)
    at exports._exceptionWithHostPort (util.js:897:20)
    at Server._listen2 (net.js:1221:19)
    at listen (net.js:1270:10)
    at net.js:1379:9
    at doNTCallback3 (node.js:452:9)
    at process._tickCallback (node.js:358:17)
```

**Comment by gordonwritescode** [comment]
Fixed - will include in next release

**Comment by littleskunk** [comment]
My local ip address is now working. My linux NAS is connected. Thank you for the fix.
```
 :STORJ: {warn} you are not bound to a public address, trying traversal strategies...
 :STORJ: {info} node created with nodeID a89b7babbd7b4071b9e6e605734223620dc301ce
 :STORJ: {info} subscribing to topic "56ce3e837f575827cb5a94e2b609756a48fa4a3882f5e762b262af31f432878d"
 :STORJ: {warn} could not connect to NAT device via UPnP
 :STORJ: {info} attempting to open connection tunnel...
 :STORJ: {info} established tunnel, you are: http://a89b7bab.tunnel.metadisk.org
```

Invalid ip address is still possible but i don't see a problem with it.
