### ISSUE TITLE
unable to run storj in npm

### ISSUE THREAD

**Issue by dlmac** [Storj/node-storj#26]
after installing node and running the install.

C:\Windows\System32>storj
path.js:8
    throw new TypeError('Path must be a string. Received ' +
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.win32.join (path.js:221:5)
    at Object.<anonymous> (C:\Users\danm2\AppData\Roaming\npm\node_modules\storj\bin\storj.js:19:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

**Comment by gordonwritescode** [comment]
Fixed in `master` - will include in next release
