### ISSUE TITLE
Install fails under Synology NAS

### ISSUE THREAD

**Issue by subwolf** [Storj/node-storj#27]
I can install node-storj fine on my own box, but the NAS is another case entirely. From my chroot I get:

```
root@subwolf-nas:~/node-storj# npm install .
npm WARN unmet dependency /root/node-storj/node_modules/bitcore-lib requires bs58@'=2.0.0' but will load
npm WARN unmet dependency /root/node-storj/node_modules/bs58,
npm WARN unmet dependency which is version 3.0.0
npm WARN unmet dependency /root/node-storj/node_modules/jsdoc requires async@'~1.4.0' but will load
npm WARN unmet dependency /root/node-storj/node_modules/async,
npm WARN unmet dependency which is version 1.5.2
npm WARN unmet dependency /root/node-storj/node_modules/browserify/node_modules/module-deps requires readable-stream@'^1.1.13' but will load
npm WARN unmet dependency /root/node-storj/node_modules/browserify/node_modules/readable-stream,
npm WARN unmet dependency which is version 2.0.5
npm WARN unmet dependency /root/node-storj/node_modules/browserify/node_modules/crypto-browserify/node_modules/browserify-sign/node_modules/browserify-rsa requires bn.js@'^4.1.0' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /root/node-storj/node_modules/browserify/node_modules/crypto-browserify/node_modules/browserify-sign/node_modules/elliptic requires bn.js@'^4.0.0' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /root/node-storj/node_modules/browserify/node_modules/crypto-browserify/node_modules/diffie-hellman/node_modules/miller-rabin requires bn.js@'^4.0.0' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /root/node-storj/node_modules/browserify/node_modules/crypto-browserify/node_modules/public-encrypt/node_modules/browserify-rsa requires bn.js@'^4.1.0' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /root/node-storj/node_modules/browserify/node_modules/insert-module-globals/node_modules/combine-source-map/node_modules/inline-source-map requires source-map@'~0.4.0' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /root/node-storj/node_modules/browserify/node_modules/labeled-stream-splicer/node_modules/stream-splicer requires readable-stream@'^1.1.13-1' but will load
npm WARN unmet dependency /root/node-storj/node_modules/browserify/node_modules/readable-stream,
npm WARN unmet dependency which is version 2.0.5
npm WARN unmet dependency /root/node-storj/node_modules/browserify/node_modules/labeled-stream-splicer/node_modules/stream-splicer/node_modules/readable-wrap requires readable-stream@'^1.1.13-1' but will load
npm WARN unmet dependency /root/node-storj/node_modules/browserify/node_modules/readable-stream,
npm WARN unmet dependency which is version 2.0.5
```

Then when trying to run the app:

```
root@subwolf-nas:~/node-storj# /usr/bin/nodejs bin/storj.js

module.js:340
    throw err;
          ^
Error: Cannot find module './lib/crypto/bn'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/node-storj/node_modules/bitcore-lib/index.js:20:21)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
```

**Comment by gordonwritescode** [comment]
what version of node are you running?

**Comment by subwolf** [comment]
v0.10.29, installed chroot environment is Debian Jessie.

**Comment by gordonwritescode** [comment]
Ah, you installed node with APT? The Jessie repository's `nodejs` package is quite old. Install node using NVM (check the README). 

Then you can use:

```
npm install -g storj
``` 

That will install the CLI `storj` program globally.

**Comment by subwolf** [comment]
NAS is Synology 1515+ running DSM 5.2-5644 Update 5

**Comment by subwolf** [comment]
Much better, thanks.
